# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: ncs_ssh
      url-base: git@github.com:nrfconnect

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: pull/27711/head
      import: true
    - name: nrf-802154
      remote: ncs_ssh
      repo-path: sdk-nrf-802154
      path: nrf-802154
      revision: pull/719/head
