# This file defines a GitHub action used to generate the body content for a pull request comment,
# providing details and quick access links to the documentation preview generated for that PR.
#
# Input Parameters:
#   - preview_url:       URL for the deployed documentation preview (GitHub Pages).
#   - changed_docs:      JSON array listing the documentation files changed in the PR.
#   - build_timestamp:   Timestamp (in UTC or specified format) when the docs preview was built.
#   - commit_sha:        Short SHA for the commit associated with the docs preview.

name: 'Generate Documentation Comment'
description: 'Generates PR comment body for documentation preview'

inputs:
  preview_url:
    description: 'GitHub Pages preview URL'
    required: true
  changed_docs:
    description: 'JSON array of changed documentation files'
    required: true
  build_timestamp:
    description: 'Build timestamp'
    required: true
  commit_sha:
    description: 'Short commit SHA'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Generate comment body
      shell: bash
      env:
        PREVIEW_URL: ${{ inputs.preview_url }}
        CHANGED_DOCS: ${{ inputs.changed_docs }}
        BUILD_TIMESTAMP: ${{ inputs.build_timestamp }}
        COMMIT_SHA: ${{ inputs.commit_sha }}
      run: |
        preview_url="$PREVIEW_URL"
        changed_docs="$CHANGED_DOCS"
        build_timestamp="$BUILD_TIMESTAMP"
        commit_sha="$COMMIT_SHA"

        # Initialize comment.md file
        echo "## Documentation Preview" > comment.md
        echo "" >> comment.md
        echo "The documentation has been built successfully. You can view the preview here: [preview]($preview_url/index.html)" >> comment.md
        echo "" >> comment.md
        echo "**Generated at**: \`$build_timestamp\` with commit \`$commit_sha\`." >> comment.md
        
        # Add links to changed files
        # Parse JSON and get count of items
        doc_count=$(echo "$changed_docs" | jq -r 'if type == "array" then length else 0 end' 2>/dev/null || echo "0")
        
        # Always show details section to ensure GitHub renders it
        # Check if we have any files to show
        has_files=false
        if [ "$doc_count" != "0" ] && [ "$doc_count" != "null" ] && [ -n "$doc_count" ]; then
          # Verify it's actually a number and > 0
          if [ "$doc_count" -gt 0 ] 2>/dev/null; then
            has_files=true
          fi
        fi
        
        echo "" >> comment.md
        echo "<details>" >> comment.md
        echo "<summary>Expand to view changed pages</summary>" >> comment.md
        echo "" >> comment.md
        
        if [ "$has_files" = "true" ]; then
          echo "" >> comment.md
          echo "" >> comment.md
          echo "| File | Preview |" >> comment.md
          echo "| ---- | ------- |" >> comment.md
          while IFS= read -r file; do
            if [ -n "$file" ] && [ "$file" != "null" ]; then
              html_path=$(echo "$file" | sed 's|^docs/||' | sed 's|\.rst$|.html|' | sed 's|\.md$|.html|')
              if [[ "$html_path" == */index.html ]]; then
                html_path="${html_path}"
              fi
              echo "| \`$file\` | [View]($preview_url/$html_path) |" >> comment.md
            fi
          done < <(echo "$changed_docs" | jq -r '.[]' 2>/dev/null)
        else
          echo "No documentation files were changed in this PR." >> comment.md
        fi
        
        echo "" >> comment.md
        echo "</details>" >> comment.md

        echo "" >> comment.md
        echo "---" >> comment.md
        echo "" >> comment.md
        echo "> **Note:** The preview will be available after GitHub Pages deployment completes (usually 1-2 minutes). Ensure that **generated at** timestamp is up to date. If the Pull Request is stale for more than 30 days, the preview may be deleted. In this case, please update the Pull Request, or re-run the Build Documentation workflow to generate a new preview." >> comment.md

        echo "Comment content:"
        cat comment.md
