#
# Copyright (c) 2026 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#


# Fixme, the new ECC handling is broken, and let's disable the new feature for now for testing.
# If cracen is fixed, we can enable this again.
CONFIG_CRACEN_ECC_COUNTERMEASURES=n
