# This GitHub Action prepares documentation for deployment to GitHub Pages.
# 

name: 'Prepare Docs for Pages'
description: 'Prepare documentation for GitHub Pages deployment'

inputs:
  docs_dir:
    description: 'Path to the directory containing built documentation'
    required: true
  target_path:
    description: 'Target path within the site (e.g., "pr-preview/pr-123" or "latest")'
    required: true
  existing_pages_dir:
    description: 'Path to existing site content'
    required: false
    default: '_existing_pages'
  output_dir:
    description: 'Output directory for the prepared site'
    required: false
    default: '_site'

outputs:
  site_dir:
    description: 'Path to the prepared site directory'
    value: ${{ steps.prepare.outputs.site_dir }}

runs:
  using: 'composite'
  steps:
    - name: Prepare site directory
      id: prepare
      shell: bash
      env:
        DOCS_DIR: ${{ inputs.docs_dir }}
        TARGET_PATH: ${{ inputs.target_path }}
        EXISTING_DIR: ${{ inputs.existing_pages_dir }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        # Create output directory
        mkdir -p "${OUTPUT_DIR}"

        # Copy existing pages content if available (preserves other PR previews)
        if [ -d "${EXISTING_DIR}" ] && [ "$(ls -A ${EXISTING_DIR} 2>/dev/null)" ]; then
          echo "Copying existing pages content..."
          cp -r "${EXISTING_DIR}"/* "${OUTPUT_DIR}/" 2>/dev/null || true
          rm -rf "${OUTPUT_DIR}/.git"  # Remove git directory if present
        fi

        # Ensure .nojekyll exists (prevents Jekyll processing)
        touch "${OUTPUT_DIR}/.nojekyll"

        # Prepare target directory
        FULL_TARGET="${OUTPUT_DIR}/${TARGET_PATH}"
        rm -rf "$FULL_TARGET"
        mkdir -p "$FULL_TARGET"

        # Copy built docs to target directory
        cp -r "${DOCS_DIR}"/* "$FULL_TARGET/"

        echo "site_dir=${OUTPUT_DIR}" >> $GITHUB_OUTPUT
