name: Documentation Remove

permissions:
  contents: read

on:
  pull_request_target:
    types: [closed]
    branches:
      - main
      - 'v*-branch'

jobs:
  remove:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.repository.default_branch }}
          sparse-checkout: .github

      - name: Load doc add-on config
        uses: ./.github/actions/load-doc-config

      - name: Try removal of PR-docs
        env:
          AZCOPY_CONCURRENCY_VALUE: 3000
          NCS_DOC_SAS_PRS: ${{ secrets.NCS_DOC_SAS_PRS }}
        run: |
          azcopy rm "${{ vars.NCS_DOC_PR_STORAGE_URL }}addons/${{ env.DOC_ADDON_NAME }}/PR-${{ github.event.number }}?${NCS_DOC_SAS_PRS}" --recursive=true || true
